### ISSUE TITLE
Make stuff pretty Part II

### ISSUE THREAD

**Issue by jtkaufman737** [jtkaufman737/HacktoberfestShoutout#2]
If we get the HTML page going and someone wants to add a css framework, that would be awesome! If you don't have a favorite, some cool/easy/minimalist ones you may like are: 
- Skeleton
- Milligram
- Wing * personal fav 
- Pure
- Bulma

**Comment by ElleinadCZ** [comment]
Hey!
It's been a while since I had some CSS work to do, I'd love to help out! Happy Hacktoberfest by the way!

**Comment by jtkaufman737** [comment]
To you as well @ElleinadCZ ! I think the person doing the HTML got started already, so if you sit tight I'll have an eye out for that pull request too. Once it is done, the css is all yours.

**Comment by ElleinadCZ** [comment]
Thanks a bunch!

**Comment by jtkaufman737** [comment]
Whoops, just realized I wasn't clear enough when I said 'Make things pretty' - someone else made the markup more attractive but I'm going to set up an HTML page real quick. I'll merge that in and then feel free to start on the CSS

**Comment by jtkaufman737** [comment]
Cooooool all set, go for it!

**Comment by jtkaufman737** [comment]
So appreciate your work! Happy hacking
