### ISSUE TITLE
Make Stuff Pretty Part III - Code Snippet

### ISSUE THREAD

**Issue by jtkaufman737** [jtkaufman737/HacktoberfestShoutout#5]
So unfortunately this is a little dependent on pull requests from the last two issues, so bear with me! Once we have a basic HTML shell and some CSS, it would be cool if we could add something that looked like a little code snippet to that page - one of those boring code-y looking fonts like Consolas or something, maybe? I'll leave it up to you!

**Comment by Evie-Skinner18** [comment]
Never done something like that before so I'd like to do it!

**Comment by Evie-Skinner18** [comment]
Submitted a pull request for this issue  :+1:

**Comment by jtkaufman737** [comment]
Thank you so much! Looking great
